### ISSUE TITLE
Health Check disable option

### ISSUE THREAD

**Issue by valecloud** [fradelg/docker-mysql-cron-backup#132]
Is possible to disable the health check?
In our observability, ton of logs are generated. 17k per hour with 6 backups containers in our env.

Thanks.
Thiago

**Comment by fradelg** [comment]
I don't think it's a good idea to disable the healthcheck. You can override the default healthcheck to suit your needs:

https://docs.docker.com/reference/compose-file/services/#healthcheck

**Comment by valecloud** [comment]
for me, this is working fine.
Thanks.
