### ISSUE TITLE
Latest symlink

### ISSUE THREAD

**Issue by johnmarcou** [fradelg/docker-mysql-cron-backup#19]
Hi,

First of all, thank you for this docker image !

I found an issue about the latest symlink, which should point to the new created archive, not the temp backup. It's here: https://github.com/fradelg/docker-mysql-cron-backup/blob/7e99a5df2a23e9ea12c7420398886df6e2c03336/backup.sh#L17-L19

Which IMO should be: 
`ln -s "$FILENAME".gz "$LATEST"`

Cheers.

**Comment by fradelg** [comment]
Fixed by @mmartinortiz in pull request #18
