### ISSUE TITLE
using secrets

### ISSUE THREAD

**Issue by judos** [fradelg/docker-mysql-cron-backup#23]
Hi there,
I like your docker image because it's very easy to use and phpmyadmin supports the .sql.gz by default.

Does the image support secret to set the db password?

**Comment by fradelg** [comment]
Hi,

thanks for using this image!

Regarding the secrets I am sure what you mean. You can always pass credentials using environment variables in your session:

```bash
export MYSQL_PASS=<secret>
docker run -e MYSQL_PASS fradelg/docker-mysql-cron-backup
```

If you want to use docker secrets, you can overwrite the entrypoint of the image with your own shell script to read those secrets in an environment variable. Take a look at this answer in StackOverflow:

https://stackoverflow.com/questions/48094850/docker-stack-setting-environment-variable-from-secrets

I hope it helps you
