### ISSUE TITLE
Change the value of max_binlog_cache_size

### ISSUE THREAD

**Issue by odunybrad** [fradelg/docker-mysql-cron-backup#25]
Thanks for providing this useful container. 

I am doing a research aiming at finding issues in configuration files. I have a question about one MySQL config: `max_binlog_cache_size`. It seems the [official document](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_cache_size) says "The maximum recommended value is 4GB; this is due to the fact that MySQL currently cannot work with binary log positions greater than 4GB."

However, the default value is 18446744073709551615, which is much larger than the recommended value. 

Shall we change the value to 4GB? 
Thanks!

**Comment by fradelg** [comment]
This is a server-side MySQL question and you should place your question in another repo. It seems to me that it depends whether you want to get an error message on big transactions or not. Take into account that MySQL can use the disk when the transaction does not fit in memory.

Check this answer for more information:

https://stackoverflow.com/questions/37813819/mysql-max-binlog-cache-size-vs-binlog-cache-size
