### ISSUE TITLE
"Halt" Database on mysqldump

### ISSUE THREAD

**Issue by hasechris** [fradelg/docker-mysql-cron-backup#42]
Hi,

i think you should put the parameter `--single-transaction` into your mysqldump statement. This is according to this answer: https://dba.stackexchange.com/a/30847

The Problem, which is solved by the mentioned parameter is the following: In big databases with a lot of reads and writes all the time the data in the mysqldump would differ timewise between the tables.

Greetings
hasechris

**Comment by fradelg** [comment]
Hi @hasechris ,

Can you make a pull request including the suggested change?

Thanks!

**Comment by hasechris** [comment]
Please have a look at pull request #43 @fradelg

**Comment by fradelg** [comment]
Thanks! Can you test the "latest" tag in your docker container?

**Comment by hasechris** [comment]
Tested and fully working! Thank you :)
