### ISSUE TITLE
restore with command wont work with Hyphen in database name

### ISSUE THREAD

**Issue by SamLoys** [fradelg/docker-mysql-cron-backup#49]
Hello,

I tried to do a backup with the command `docker container exec <your_mysql_backup_container_name> /restore.sh /backup/<your_sql_backup_gz_file>
` but I get the message that the database is unkown. This is probably because the database contained a `-` in the name. Databases that do not make use of a `-` work fine. Do you maybe have a solution for this or should I recreate all my databases without a hyphen in the name? 
![image](https://user-images.githubusercontent.com/32015146/119170068-0991a280-ba63-11eb-95c1-ca326abbcc75.png)

**Comment by fradelg** [comment]
Try using the image tagged with support-hyphen-in-db-name. If it works, I will merge the change in master

**Comment by SamLoys** [comment]
Amazing thanks! it seems to work perfectly now
![image](https://user-images.githubusercontent.com/32015146/119391558-c63b6c00-bcce-11eb-9cb2-08a9ceb16669.png)
