### ISSUE TITLE
xrealloc: cannot allocate

### ISSUE THREAD

**Issue by leranp** [fradelg/docker-mysql-cron-backup#62]
First time that i am using the restore option, but there is something worng
bash-5.1# /restore.sh /backup/202111200200.homeassistant.sql.gz           /restore.sh: xrealloc: cannot allocate 2147478528 bytes

**Comment by fradelg** [comment]
Hi,

This seems like an out of memory issue, not a problem with the docker image. Have you checked that you have enough memory in the host to load these 2,147 GB? Can you try it again?

Regards

**Comment by leranp** [comment]
> Hi,
> 
> This seems like an out of memory issue, not a problem with the docker image. Have you checked that you have enough memory in the host to load these 2,147 GB? Can you try it again?
> 
> Regards

Yes, i have enough memory , about 350GB.
I tried couple of time with different backups

**Comment by fradelg** [comment]
Have you set up the MYSQL_DB environment variable? I cannot help you from here but you have to check which line of the shell script restore.sh is giving this error. You can try to comment everything and then uncomment line by line since the beginning of the script.

**Comment by leranp** [comment]
> Have you set up the MYSQL_DB environment variable? I cannot help you from here but you have to check which line of the shell script restore.sh is giving this error. You can try to comment everything and then uncomment line by line since the beginning of the script.

No, i didn't used the option, i will try to uncomment lines
