### ISSUE TITLE
Restore one DB from list

### ISSUE THREAD

**Issue by ay1man4** [fradelg/docker-mysql-cron-backup#66]
Hi,

In current configuration for **auto restore** during intial docker startup, restore script will restore all databases configured in environment variable _MYSQL_DATABASE_ which is defaulted to `--all-databases`
If we set _INIT_RESTORE_LATEST_, during startup it will check _MYSQL_DATABASE_ and restore all databases set on it.
The problem is if we want to restore one database only, if change _MYSQL_DATABASE_, this will impact the backup.

I suggest to add another environment variable for restore databases for example **MYSQL_DATABASE_RESTORE**, so backup will not be impacted and user will have control to restore any database just by changing the value of _MYSQL_DATABASE_RESTORE_ and set  the flag _INIT_RESTORE_LATEST_.

**Comment by fradelg** [comment]
I get what you mean. I will think about it but you can always run the container with the restore.sh as command to restore your specific DB and then backup the others. Please, check the documentation:

https://github.com/fradelg/docker-mysql-cron-backup#restore-using-a-compose-file
