### ISSUE TITLE
Remove double quotes from $MYSQLDUMP_OPTS 

### ISSUE THREAD

**Issue by moty66** [fradelg/docker-mysql-cron-backup#72]
https://github.com/fradelg/docker-mysql-cron-backup/blob/42312b94a39cd09f587f7a2328a7d63732fda4af/backup.sh#L24

In my case, I need to specify multiple options, but because of the double quotes it fails

example: 
MYSQLDUMP_OPTS=--quick --lock-tables=false --compact --opt

**Comment by fradelg** [comment]
ok, thanks for your contribution
