### ISSUE TITLE
Request: Backup for multiple MySQL containers

### ISSUE THREAD

**Issue by a1ad** [fradelg/docker-mysql-cron-backup#84]
Hi,

Now I need to spin a new "docker-mysql-cron-backup" container for each MySQL docker container.
I would be awesome to somehow have 1 backup-container that can access all my MySQL containers across different compose stacks to make a backup. 

Is something like that feasible?

**Comment by fradelg** [comment]
Hi, thanks for using this project.

However, I think this is beyond the original goal of this project to keep things as simple as possible working like a sidecar for your MySQL databases.

Best
