### ISSUE TITLE
Problem with dial

### ISSUE THREAD

**Issue by Abhi5h3k** [fradelg/docker-mysql-cron-backup#97]
**Error:**
```
Waiting for: tcp://mysql:3306
Problem with dial: dial tcp: lookup mysql on 127.0.0.11:53: server misbehaving. Sleeping 1s
```

I'm getting the above error, Does anyone know what can be the issue!!

I have tried running the command and docker-compose. Getting same error.

**Comment by fradelg** [comment]
You have to look for errors in the log messages during the booting of the MariaDB/MySQL service because the backup container cannot connect to it

**Comment by Abhi5h3k** [comment]
I'm able to connect to the MySQL container from workbench and all other application are working fine with it. I don't know why it's not connecting to backup container. Also there is no error in MySQL logs. 

any other suggestion!

**Comment by fradelg** [comment]
It seems like a networking issue of your docker daemon so it's very hard to solve from here.

Google it a little bit to look for possible solutions like these:

https://stackoverflow.com/questions/28332845/docker-network-issue-server-misbehaving

https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/630
